### ISSUE TITLE
Need to clear the cache?

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#40] opened 2020-03-21 09:39 UTC
I think this is a bug report.
When I tried to make a video of Ephesians Intro in BK 0.3.2, I had first made a video of Ephesians 1, then went back and chose "Intro" and made another video. The resulting video had the audio for the Intro, but the text that appeared was the text of Ephesians 1 still.
Closing the program, re-opening it, and then making the video again solved the problem. However, it would be more convenient not to have to do that between every video.

**Comment by Hiro-Nakamura** [comment] 2020-04-20 08:19
This is the same as #50

**Comment by megahirt** [comment] 2020-06-13 02:25
Closing as duplicate of #50 and #58.

**Closed by megahirt** 2020-06-13 02:25 UTC
Labels: duplicate
